[khat]
# This is an internal value used to determine whether your config is valid
# for the current instance of the bot. Automatic migrations might be made in order
# to keep you updated, so do NOT manually change this!
version = "3.0"
# A list with strings with webhook endpoint URLs
# See: https://tywrap-studios.tiazzz.me/r/webhooks
webhooks = []